name: Scribe Signed Git Commit SBOM
on:
  workflow_dispatch:
env:
  IMAGE_NAME: ${{ github.repository }}:${{ github.sha }}
  AUTHOR_NAME: Jane Doe
  AUTHOR_EMAIL: info@scribesecurity.com
  AUTHOR_PHONE: 111-1111-11
  SUPPLIER_NAME: Scribe-Security
  SUPPLIER_URL: www.scribesecurity.com
  SUPPLIER_EMAIL: info@scribesecurity.com
  SUPPLIER_PHONE: 001-001-0011
  USER_DATA: service-binding
  PRODUCT_VERSION: "9"
  PRODUCT_NAME: Scribe-Synthetic-Testing
  COMPANY_CA: ${{ secrets.COMPANY_CA }}
  SIGNER_CERT: ${{ secrets.SIGNER_CERT }}
  SIGNER_KEY: ${{ secrets.SIGNER_KEY }}
  API: ${{ secrets.api }}
  
jobs:          
  generate-source-sbom:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
    - uses: actions/checkout@v3
    - name: Generate signed SBOM for repo content
      uses: scribe-security/action-bom@master
      with:
        target: 'git:.'
        fetch-depth: 0
        scribe-enable: true
        components: commits,packages,files,dep
        product-key: "Test_004"
        product-version: ${{ env.PRODUCT_VERSION }}
        scribe-client-secret: ${{ secrets.SCRIBE_TOKEN }}
        label: is_git_commit
        format: attest
        author-name: $AUTHOR_NAME
        author-email: $AUTHOR_EMAIL
        author-phone: $AUTHOR_PHONE
        supplier-name: $SUPPLIER_NAME
        supplier-url: $SUPPLIER_URL
        supplier-email: $SUPPLIER_EMAIL 
        supplier-phone: $SUPPLIER_PHONE
        force: true

        
  generate-provenance:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: create slsa provenance
      id: slsa_provenance
      uses: scribe-security/action-slsa@master
      with:
        target: 'docker:github-action:${{ github.sha }}'
        scribe-enable: true
        product-key: ${{ env.PRODUCT_NAME }}
        product-version: ${{ env.PRODUCT_VERSION }}
        scribe-client-secret: ${{ secrets.SCRIBE_TOKEN }}
        format: attest
        config: .valint.yaml
        
  verify-policy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: verify slsa1
      id: slsa_ver1
      uses: scribe-security/action-verify@master
      with:
        target: 'docker:github-action:${{ github.sha }}'
        scribe-enable: true
        product-key: ${{ env.PRODUCT_NAME }}
        product-version: ${{ env.PRODUCT_VERSION }}
        scribe-client-secret: ${{ secrets.SCRIBE_TOKEN }}
        format: attest
        config: .valint.yaml
        rule: slsa/l1-provenance-exists@v1
        verbose: 2
    - name: verify slsa2
    
      id: slsa_ver2
      uses: scribe-security/action-verify@master
      with:
        target: 'docker:github-action:${{ github.sha }}'
        scribe-enable: true
        product-key: ${{ env.PRODUCT_NAME }}
        product-version: ${{ env.PRODUCT_VERSION }}
        scribe-client-secret: ${{ secrets.SCRIBE_TOKEN }}
        format: attest
        config: .valint.yaml
        rule: slsa/l2-provenance-authenticated@v1
        verbose: 2
